# Generated by Django 2.1.7 on 2019-03-24 18:39

import Photos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=Photos.models.ger_photo_name)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('count', models.IntegerField()),
                ('zip', models.FileField(blank=True, upload_to=Photos.models.gen_zip_name)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Photos.ProfilePhotos'),
        ),
    ]
